const Joi = require('joi');

const NotificationSchema = Joi.object({
  id: Joi.string().optional(), // Auto-generated by Firestore
  userId: Joi.string().when('isAdminMessage', {
    is: true,
    then: Joi.optional(), // userId not required for admin messages
    otherwise: Joi.required() // userId required for user messages
  }),
  message: Joi.string().required(),
  type: Joi.string().valid('system', 'admin').required(),
  isAdminMessage: Joi.boolean().default(false),
  createdAt: Joi.object().required(), // Firebase Admin Timestamp
  expiresAt: Joi.object().optional() // Firebase Admin Timestamp
})
.prefs({ abortEarly: false });

module.exports = NotificationSchema;
