import Joi from 'joi';
import { Timestamp } from 'firebase/firestore';

const NotificationSchema = Joi.object({
  archived: Joi.boolean().default(false).required(), // Not for archiving. Simply to align with access control rules.
  id: Joi.string().optional(), // Auto-generated by Firestore
  userId: Joi.string().when('isAdminMessage', {
    is: true,
    then: Joi.optional(), // userId not required for admin messages
    otherwise: Joi.required() // userId required for user messages
  }),
  message: Joi.string().required(),
  type: Joi.string().valid('system', 'admin').required(),
  isAdminMessage: Joi.boolean().default(false),
  reservationId: Joi.string().optional(), // For refund notifications to link to reservation
  createdAt: Joi.object().instance(Timestamp).required(), // Firebase Admin Timestamp  
  expiresAt: Joi.object().instance(Timestamp).optional() // Firebase Admin Timestamp 
})
.prefs({ abortEarly: false });

export default NotificationSchema;
