import Joi from 'joi';
import { Timestamp } from 'firebase/firestore';

const NotificationSchema = Joi.object({
  id: Joi.string().optional(), // Auto-generated by Firestore
  userId: Joi.string().when('isAdminMessage', {
    is: true,
    then: Joi.optional(), // userId not required for admin messages
    otherwise: Joi.required() // userId required for user messages
  }),
  message: Joi.string().required(),
  type: Joi.string().valid('system', 'admin').required(),
  isAdminMessage: Joi.boolean().default(false),
  createdAt: Joi.object().instance(Timestamp).required(),
  expiresAt: Joi.object().instance(Timestamp).optional()
})
.prefs({ abortEarly: false });

export default NotificationSchema;
